version: "3.8"

services:
  cosmos-emulator:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest
    container_name: regata-cosmos-emulator
    restart: unless-stopped
    tty: true
    environment:
      AZURE_COSMOS_EMULATOR_PARTITION_COUNT: 1
      AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE: "true"
      AZURE_COSMOS_EMULATOR_IP_ADDRESS_OVERRIDE: 0.0.0.0
    ports:
      - "8081:8081"
      - "8900:8900"
      - "10250-10255:10250-10255"
    volumes:
      - cosmos-emulator-data:/data/cosmosdb
    command:
      - "--log-path=/data/log"
      - "--endpoint=https://0.0.0.0:8081"
      - "--key=C2y6yDjf5/R+ob0N8A7Cgv30VRjYHYfC6az4g=="
    healthcheck:
      test: ["CMD", "curl", "-f", "https://localhost:8081/_explorer/emulator.pem", "--insecure"]
      interval: 30s
      timeout: 10s
      retries: 10

volumes:
  cosmos-emulator-data:
